### ISSUE TITLE
Tag version 2.0.0 so it works with go mod

### ISSUE THREAD

**Issue by apple314159** [farshidtz/mqtt-match#2]
When using this with go 1.11 and go mod, it tries to retrieve the tag v1.0.0 and complains it can't find a module.

This can be fixed by creating a tag of the go version (say v2.0.0)

**Comment by farshidtz** [comment]
The tag was from the original repository. I moved it to the head but then it created issues because go get wasn't getting the new code. I then added another tag. You may still need to remove the old checksums from go.sum. 

This was my first interaction with go mod and I didn't know how it works. I should have listened to you.
